# Generated by Django 4.2.2 on 2023-06-09 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendUtilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilityuser', to=settings.AUTH_USER_MODEL)),
                ('userblocked', models.ManyToManyField(blank=True, related_name='blocked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
