# Generated by Django 4.1.8 on 2023-08-07 21:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath)),
                ('tagline', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bio', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('profile_link1_text', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('profile_link1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('profile_link2_text', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('profile_link2', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
