# Generated by Django 4.2.2 on 2023-06-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
