# Generated by Django 4.2.2 on 2023-06-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_link1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_link1_text',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_link2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_link2_text',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
