# Generated by Django 4.2.2 on 2023-06-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_profile_link1_account_profile_link1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_link1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_link1_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_link2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_link2_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
