# Generated by Django 4.2.2 on 2023-06-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_profile_link1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
