# Generated by Django 4.2.2 on 2023-06-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_friendlist_friendrequest_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
