# Generated by Django 4.2.2 on 2023-06-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_remove_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
