# Generated by Django 4.1.8 on 2023-08-11 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mediashare.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to=mediashare.models.get_sharedmedia_filepath)),
                ('edittime', models.DateTimeField(auto_now=True, verbose_name='edit time')),
                ('seen', models.BooleanField(default=False)),
                ('mediareceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediareceiver', to=settings.AUTH_USER_MODEL)),
                ('mediasender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediasender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-edittime',),
            },
        ),
    ]
