# Generated by Django 4.1.8 on 2023-08-07 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NowPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.BooleanField(default=False)),
                ('playing', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('artist', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('album', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('progress', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=6, null=True)),
                ('listentime', models.DateTimeField(auto_now=True, verbose_name='listen time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-listentime', '-title'),
            },
        ),
    ]
