# Generated by Django 4.2.2 on 2023-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ('edittime',)},
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='edittime',
            field=models.TimeField(auto_now=True, verbose_name='edit time'),
        ),
    ]
