# Generated by Django 4.2.2 on 2023-06-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_alter_textmessage_options_alter_textmessage_edittime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ('-edittime',)},
        ),
    ]
